### ISSUE TITLE
Where can I found my nano.bash file?

### ISSUE THREAD

**Issue by hadrien-toma** [binaryphile/y2s#3]
Hi there, I would like to try `y2s` but it fails to source with the following:
```sh
y2s.bash: line 4: nano.bash: No such file or directory
y2s.bash: line 19: _ret: command not found
y2s.bash: line 19: _ret: command not found
y2s.bash: line 19: _ret: command not found
y2s.bash: line 19: _ret: command not found
y2s.bash: line 19: _ret: command not found
y2s.bash: line 19: _ret: command not found
```

This is my environment:
- `bash --version`:
```sh
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
- `nano --version`:
```sh
 GNU nano version 2.2.6 (compiled 14:12:08, Oct  1 2012)
 (C) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
 2008, 2009 Free Software Foundation, Inc.
 Email: nano@nano-editor.org	Web: http://www.nano-editor.org/
 Compiled options: --disable-wrapping-as-root --enable-color --enable-extra --enable-multibuffer --enable-nanorc --enable-utf8
```

Do you know what I am missing?

**Comment by binaryphile** [comment]
https://github.com/binaryphile/nano

The Installation section of the readme notes that nano.bash is a small library of mine which needs to be available on your path so that the command "source nano.bash" works (you can test whether does is by running that command at the cli).  I've pasted the link to it above.

It doesn't have anything to do with nano the editor, btw.  Just a few functions I use across many projects.

Your bash version looks fine as well.

Thanks for the interest!

**Comment by hadrien-toma** [comment]
Aaah, I was wondering why the hell the `nano` text editor was required, I see now^^. So with your `nano.bash` library, I am able to run `y2s` but trying your example, it seems that I have wrong results for the array part. I am opening an other issue about that.

Thank you to bring my interest! Being able to fully interface `YAML` files with `bash` scripts is a keypiece!
